{% set name = "scaleapi" %}
{% set version = "2.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scaleapi-{{ version }}.tar.gz
  sha256: fb653d958b9430eec548e8e77134dc1ad1f62bf14e445fea4fbbc8396bc6c4a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests >=2.25.0
    - urllib3 >=1.26.0

test:
  imports:
    - scaleapi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scaleapi/scaleapi-python-client
  summary: The official Python client library for Scale AI, the Data Platform for AI
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shaun-scale
    - fatihkurtoglu
